baseURL = "https://www.quickqueue.com.my"
disableLanguages = ["fr"]
disqusShortname = "Quick Queue Sdn Bhd"
googleAnalytics = ""
paginate = "6"
summaryLength = "10"
theme = "Quick Queue Web Site"
title = "Event Platform for In-Person and Hybrid Events | Quick Queue"
[markup.goldmark.renderer]
unsafe = true
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
